### ISSUE TITLE
Direction should have precedence 

### ISSUE THREAD

**Issue by dobbobolina** [Solid-Interactive/magic-focus-finder#28]
I noticed in the demo that navigating was pretty unnatural, you could not go to where you wanted / thought you were going to go some of the time. One way I have gotten around this in the past was first looking for the next element in a completely straight line from the element you are currently on like :

![screen shot 2015-06-02 at 4 19 30 pm](https://cloud.githubusercontent.com/assets/4184023/7949507/3769c9b2-0943-11e5-90c3-02f8c1e51fc9.png)

because you would expect to go to that one even if its across the screen and further than the ones above and below. If nothing is found, then use the geometry approach with triangles.

![screen shot 2015-06-02 at 4 19 37 pm](https://cloud.githubusercontent.com/assets/4184023/7949508/3ecd03c2-0943-11e5-9a07-17777a1e36d8.png)

**Comment by Duder-onomy** [comment]
Yeah totally, this relates to #24 and #25.

We were going to give the user the ability to configure multiple finding algorithms, then for certain elements, they can use data attributes to tell the lib how to find the next one, 

like

```html
<div focusable focus-left-prefer="straight-line"></div>
```

How does that sound?

**Comment by pajtai** [comment]
mmmmmm.... ASCII art

in terms of finding algorithms we'd have 2 coefficients.... a direction, and a distance, then you could adjust the relative weights to tune your finding algorithm. e.g. 0.8 direction - weight 0.2 distance weight

**Comment by dobbobolina** [comment]
I think thats fine, but as far as weighting the algorithms, I think you might want an absolute with the direction, because the case where you really need it to work is when its on the other side of the screen, and having weights might prevent you from being able to jump to the one you want to get to. Just an opinion though, you should do whatever feels most natural.

**Comment by pajtai** [comment]
yeah, I think we'll have to play around with it and probably have both the weight and the flags like greg was suggesting (focus-prefer straight-line)...
